stages:
  - test
  - build
  - security
  - tag

include:
  - local: .gitlab/ci/gitleaks.gitlab-ci.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      - if: "$CI_COMMIT_BRANCH"
      - when: never
  - local: .gitlab/ci/test.gitlab-ci.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - buzz/**/*
          - tests/**/*
          - pyproject.toml
          - uv.lock
          - pyrightconfig.json
          - .htmlhintrc
          - buzz/Dockerfile
          - docker-compose.yml
          - maint-scripts/update_dependency_refs.py
          - .gitlab-ci.yml
          - .gitlab/ci/*.gitlab-ci.yml
      - if: "$CI_COMMIT_BRANCH"
      - when: never
  - local: .gitlab/ci/image-publish.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      - if: '$CI_COMMIT_BRANCH == "main"'
      - when: never
  - local: .gitlab/ci/security.gitlab-ci.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - buzz/**/*
          - scripts/**/*
          - pyproject.toml
          - uv.lock
          - buzz/Dockerfile
          - .gitlab/ci/security.gitlab-ci.yml
      - if: '$CI_COMMIT_BRANCH == "main"'
        changes:
          - buzz/**/*
          - scripts/**/*
          - pyproject.toml
          - uv.lock
          - buzz/Dockerfile
          - .gitlab/ci/security.gitlab-ci.yml
      - when: never

default:
  tags:
    - groundstation
