stages:
  - test
  - build
  - tag

include:
  - local: .gitlab/ci/gitleaks.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/image-publish.gitlab-ci.yml
  - local: .gitlab/ci/update-major-tag.gitlab-ci.yml
