include:
  - component: gitlab.com/gabriel.chamon/ci-components/docker-build@v1
    inputs:
      job_name: build_buzz_docker_image
      image_name: buzz
      image_path: .
      dockerfile_name: buzz/Dockerfile
      job_rules:
        - when: always
