pytest:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.14-alpine@sha256:1054a8c47beacaea07c0bbdb073e6b80a26deeb36c270593bb92c75a653d71d5
  script:
    - uv sync --group dev
    - uv run pytest --cov=buzz --cov-report=xml --cov-report=term
  rules:
    - when: always
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

htmlhint:
  stage: test
  image: node:alpine@sha256:144769ec3f32e8ee36b3cfde91e82bee25d9367b20f31a151f3f7eea3a2a8541
  script:
    - npx --yes htmlhint "buzz/pyview_templates/*.html"
  rules:
    - when: always
  allow_failure: true
