pytest:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.14-alpine@sha256:e5d88be0bc6a7ee7945a3efe25503827c0e621923ce7655c71c6a1f98e7b58e5
  script:
    - uv sync --group dev
    - uv run pytest --cov=buzz --cov-report=xml --cov-report=term
  rules:
    - when: always
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

htmlhint:
  stage: test
  image: node:alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4
  script:
    - npx --yes htmlhint "buzz/pyview_templates/*.html"
  rules:
    - when: always
  allow_failure: true
